### ISSUE TITLE
More friendly folder structure for CMakeLists.txt.

### ISSUE THREAD

**Issue by zhongjingjogy** [pabristow/quan#5]
In order to using `quan` in `CMake`, a simple `CMakeLists.txt` can be written to provide `quan` as `INTERFACE`. As the folder structure does not exist as `include/boost/quan`, so it is hard to add a prefix in the `CMakeLists.txt` to make this library to be accessed like <boost/quan>.

To solve this, it is recommended that a folder named `boost` should be created on the top of `quan`, which makes it easier to write `CMakeLists.txt`. And thus, `quan` can be added as third library by other git repository using `submodule` feature of `git` without hacking this library.

PS
There should be potential way for adding prefix to a library in CMake scripts, which seems to be a little bit difficult without advanced knowledge about CMake.

**Comment by zhongjingjogy** [comment]
I notice that there is a [pull request](https://github.com/pabristow/quan/pull/4) that does same thing as I have mentioned. It might be a clever choice to do so.

**Comment by pabristow** [comment]
Work in progress.
